package com.riffdeck.player.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF4D5C92)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFDCE1FF)
val onPrimaryContainerLight = Color(0xFF354479)
val secondaryLight = Color(0xFF595D72)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFDEE1F9)
val onSecondaryContainerLight = Color(0xFF424659)
val tertiaryLight = Color(0xFF75546F)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFD7F5)
val onTertiaryContainerLight = Color(0xFF5B3D57)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFAF8FF)
val onBackgroundLight = Color(0xFF1A1B21)
val surfaceLight = Color(0xFFFAF8FF)
val onSurfaceLight = Color(0xFF1A1B21)
val surfaceVariantLight = Color(0xFFE2E1EC)
val onSurfaceVariantLight = Color(0xFF45464F)
val outlineLight = Color(0xFF767680)
val outlineVariantLight = Color(0xFFC6C5D0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F3036)
val inverseOnSurfaceLight = Color(0xFFF1F0F7)
val inversePrimaryLight = Color(0xFFB6C4FF)
val surfaceDimLight = Color(0xFFDAD9E0)
val surfaceBrightLight = Color(0xFFFAF8FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF4F3FA)
val surfaceContainerLight = Color(0xFFEFEDF4)
val surfaceContainerHighLight = Color(0xFFE9E7EF)
val surfaceContainerHighestLight = Color(0xFFE3E1E9)

// RiffDeck rock/metal/Y2K palette — mirrors values-night/colors.xml exactly
// so Compose screens (Equalizer, About, Settings, Lyrics, etc.) and XML/View
// screens render identical colors.
val primaryDark = Color(0xFFFF5A6E)
val onPrimaryDark = Color(0xFF3A0008)
val primaryContainerDark = Color(0xFF7A1220)
val onPrimaryContainerDark = Color(0xFFFFD9DC)
val secondaryDark = Color(0xFFAEB6C2)
val onSecondaryDark = Color(0xFF1E2126)
val secondaryContainerDark = Color(0xFF3B4048)
val onSecondaryContainerDark = Color(0xFFEFF3F8)
val tertiaryDark = Color(0xFFFFB020)
val onTertiaryDark = Color(0xFF3A2600)
val tertiaryContainerDark = Color(0xFF6B4A00)
val onTertiaryContainerDark = Color(0xFFFFE4B0)
val errorDark = Color(0xFFFF6E7A)
val onErrorDark = Color(0xFF3A0008)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF15171B)
val onBackgroundDark = Color(0xFFF2F3F5)
val surfaceDark = Color(0xFF15171B)
val onSurfaceDark = Color(0xFFF2F3F5)
val surfaceVariantDark = Color(0xFF2A2E35)
val onSurfaceVariantDark = Color(0xFFA7ADB8)
val outlineDark = Color(0xFF565D68)
val outlineVariantDark = Color(0xFF3B4048)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFF2F3F5)
val inverseOnSurfaceDark = Color(0xFF1E2126)
val inversePrimaryDark = Color(0xFFB3122A)
val surfaceDimDark = Color(0xFF101215)
val surfaceBrightDark = Color(0xFF3B4048)
val surfaceContainerLowestDark = Color(0xFF0B0C0E)
val surfaceContainerLowDark = Color(0xFF1A1D22)
val surfaceContainerDark = Color(0xFF1E2126)
val surfaceContainerHighDark = Color(0xFF2A2E35)
val surfaceContainerHighestDark = Color(0xFF3B4048)